services:
  db:
    image: postgres:15
    container_name: dev-crm-db
    restart: always
    env_file:
      - .db-env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: